import * as monaco from 'monaco-editor';

export function initMonacoThemes() {
    monaco.editor.defineTheme("dracula", {
        base: "vs-dark",
        inherit: true,
        rules: [
            { token: "comment", foreground: "6272a4" },
            { token: "keyword", foreground: "ff79c6" },
            { token: "operator", foreground: "ff79c6" },
            { token: "string", foreground: "f1fa8c" },
            { token: "number", foreground: "bd93f9" },
            { token: "regexp", foreground: "f1fa8c" },
            { token: "type", foreground: "8be9fd" },
            { token: "class", foreground: "8be9fd" },
            { token: "function", foreground: "50fa7b" },
            { token: "variable.predefined", foreground: "50fa7b" },
            { token: "constant", foreground: "bd93f9" },
            { token: "delimiter", foreground: "f8f8f2" },
            { token: "invalid", foreground: "ff5555" },
        ],
        colors: {
            "editor.background": "#282a36",
            "editor.foreground": "#f8f8f2",
            "editor.selectionBackground": "#44475a",
            "editor.inactiveSelectionBackground": "#44475a99",
            "editor.lineHighlightBackground": "#44475a66",
            "editorCursor.foreground": "#f8f8f2",
            "editorIndentGuide.background": "#6272a433",
            "editorIndentGuide.activeBackground": "#6272a4",
            "editorLineNumber.foreground": "#6272a4",
            "editorLineNumber.activeForeground": "#f8f8f2",
            "editorBracketMatch.border": "#50fa7b",
            "editor.selectionHighlightBackground": "#44475a88",
            "editor.wordHighlightBackground": "#8be9fd22",
            "editor.wordHighlightStrongBackground": "#8be9fd44",
            "editorWhitespace.foreground": "#6272a44d",
            "editorGutter.background": "#282a36",
            "editorSuggestWidget.background": "#282a36",
            "editorSuggestWidget.border": "#44475a",
            "editorSuggestWidget.foreground": "#f8f8f2",
            "editorSuggestWidget.highlightForeground": "#ff79c6",
            "editorSuggestWidget.selectedBackground": "#44475a",
            "editorHoverWidget.background": "#282a36",
            "editorHoverWidget.border": "#44475a",
            "editorWidget.background": "#282a36",
            "editorWidget.border": "#44475a",
            "sideBar.background": "#282a36",
        },
    });
}